apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lgf34w1as-dotnet-basic
  janus-idp.io/tekton: lgf34w1as-dotnet-basic
  backstage.io/kubernetes-id: lgf34w1as-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lgf34w1as-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
